### ISSUE TITLE
Administrador: Dar de alta usuario

### ISSUE THREAD

**Issue by SOSA1095** [ProyectoIntegrador2018/conexion_tec#39]
Como administrador podre dar de alta diferentes usuario con tipos especificos para tener diferentes tipos de acceso a la applicacion

Tasks
- [ ]  Definir los tipos de usuario
- [ ] Agregar informacion a la base de datos
- [ ] Crear vista para dar de alta

Criterio de Aceptacion
- [ ]  Los nuevos usuario dados de alta podran entrar a la aplicacion

NOTA: Revisar esta funcionalidad junto con el issue #40 . Esto puede siginficar un cambio fuerte para el modelado y representación de datos del proyecto. Actualemente, se hacen diferentes controladores dentro de namespaces para los diferentes usuarios que hay, no se pueden crear usuarios "dinámicos"; es decir, no se le permite crear usuarios con ciertos permisos, ya que los permisos son estáticos (debido a los namespaces).

**Comment by PQbiit** [comment]
#68
