### ISSUE TITLE
Comité: Rechazar proyecto

### ISSUE THREAD

**Issue by jluisfgarza** [ProyectoIntegrador2018/conexion_tec#66]
Como Miembro  del Comité puedo rechazar proyectos para que no participen en el evento de Conexión Tec

## To Do
- [ ] Pendiente

## Criterios de aceptación
- En la base de datos, el estado del proyecto es rechazado 
- El alumno responsable podrá ver el estatus del proyecto al iniciar sesión

**Comment by HumbertoGuevara** [comment]
Duplicated #64
