### ISSUE TITLE
Modificar la semilla de la base de datos

### ISSUE THREAD

**Issue by abrilgzz** [ProyectoIntegrador2018/conexion_tec#74]
## Nombre de Tarea
Modificar la semilla de la base de datos

## Descripción de Tarea
Crear registros semilla de la base de datos modificada

## Conversación
Crear registros de prueba para la base de datos que sirvan para probar la integridad de la base de datos

## Criterios de aceptación
- [x] La base de datos está poblada con el contenido de la semilla

## OPCIONAL - Relaciones
- #73

**Comment by HumbertoGuevara** [comment]
Faltan algunas semillas para probar las cosas existentes.
