### ISSUE TITLE
Administrador: Agregar/Editar categoría de proyectos

### ISSUE THREAD

**Issue by ssandoval95** [ProyectoIntegrador2018/conexion_tec#78]
Como Administrador puedo editar y agregar categorías  para poder relacionarlas a proyectos y/o preguntas

## To Do
- [x] Crear controlador de categorías
- [x] Crear vista de categorías
- [x] CRUD de categorías
- [x] Notificación de cambios
- [x] Notificación de errores

## Criterios de aceptación
- [x] Pasa las pruebas unitarias
- [x] Pasa las pruebas de integración
- [x] Cumple con el estándar de codificación
- [x] Revisado por colega

**Comment by HumbertoGuevara** [comment]
#70
